steps:
  - label: build image
    key: build
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - name: build
                image: gradle:latest
                command: [.buildkite/steps/build.sh]
  - label: deploy
    depends_on: build
    key: deploy
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            serviceAccountName: deploy
            containers:
              - name: deploy
                image: bitnami/kubectl:latest
                command: [.buildkite/steps/deploy.sh]
  - label: curl
    key: curl
    depends_on: deploy
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - name: curl
                image: curlimages/curl:latest
                command: [curl]
                args:
                  - --no-progress-meter
                  - petclinic.petclinic
  - name: cleanup
    depends_on:
      - step: deploy
        allow_failure: true
      - step: curl
        allow_failure: true
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            serviceAccountName: deploy
            containers:
              - name: cleanup
                image: bitnami/kubectl:latest
                command: [.buildkite/steps/cleanup.sh]
