steps:
  - label: test & build image
    key: build
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - name: build
                image: gradle:latest
                command: [.buildkite/steps/build.sh]
                env:
                - name: BUILDKITE_ANALYTICS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: BUILDKITE_ANALYTICS_TOKEN
                      name: spring-petclinic-secrets
      - test-collector:
          files: "build/test-results/*.xml"
          format: "junit"
  - label: integration tests
    depends_on: build
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            serviceAccountName: deploy
            containers:
              - name: deploy
                image: portainer/kubectl-shell:latest
                command: [.buildkite/steps/integration-tests.sh]
