---
apiVersion: v1
kind: Namespace
metadata:
  name: buildkite
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer
rules:
  - apiGroups: ["appsv1", ""] # "" indicates the core API group
    resources: ["services", "deployments"]
    verbs: ["create", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy
subjects:
  - kind: ServiceAccount
    name: deploy
roleRef:
  kind: Role
  name: deployer
  apiGroup: rbac.authorization.k8s.io
